/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AiChatBot: typeof import('./../components/AiChatBot.vue')['default']
    AigcHeader: typeof import('./../components/AigcHeader.vue')['default']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    BestCollections: typeof import('./../components/Home/BestCollections.vue')['default']
    CircularImageAnimation: typeof import('./../components/CircularImageAnimation.vue')['default']
    ConnectButton: typeof import('./../components/ConnectButton.vue')['default']
    ContentExchangePlatform: typeof import('./../components/Home/ContentExchangePlatform.vue')['default']
    Dropdown: typeof import('./../components/Dropdown.vue')['default']
    DropdownItem: typeof import('./../components/DropdownItem.vue')['default']
    FileUpload: typeof import('./../components/FileUpload.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    GlassCard: typeof import('./../components/GlassCard.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    LearnNft: typeof import('./../components/Home/LearnNft.vue')['default']
    LoginEntry: typeof import('./../components/uid/LoginEntry.vue')['default']
    MakeBidModal: typeof import('./../components/MakeBidModal.vue')['default']
    MakeOfferModal: typeof import('./../components/MakeOfferModal.vue')['default']
    MoreFromCollection: typeof import('./../components/MoreFromCollection.vue')['default']
    NftPlaceholder: typeof import('./../components/Home/NftPlaceholder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StickyCardsAnimation: typeof import('./../components/Home/StickyCardsAnimation.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon.vue')['default']
  }
}
